//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worker_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Worker_Project.Models.Annotation;

    [MetadataType(typeof(WorkerAnnotation))]
    public partial class Worker
    {
        public int WorkerId { get; set; }
        public string WorkerName { get; set; }
        public decimal Salary { get; set; }
        public string Picture { get; set; }
        public int TypeId { get; set; }
    
        public virtual WorkerType WorkerType { get; set; }
    }
}
